Update patch set 4
Patch Set 4:

Great work! This time I see only one remaining fail on Java 8 and no fails on Java 7:

org.junit.experimental.theories.internal.ParameterizedAssertionError: testDirtySubmoduleWorktreeUntracked("UNTRACKED" <from allModes[2]>)
	at org.junit.experimental.theories.Theories$TheoryAnchor.reportParameterizedError(Theories.java:288)

Caused by: java.lang.AssertionError: diff should be false with mode=UNTRACKED
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.eclipse.jgit.lib.IndexDiffSubmoduleTest.testDirtySubmoduleWorktreeUntracked(IndexDiffSubmoduleTest.java:207)

I will try to rebase your patch on top of https://git.eclipse.org/r/#/c/78586/ and see if this would solve the remaining issue and probably makes your workaround for WirkingTreeIterator not needed.

Patch-set: 4
Label: Verified=0