Update patch set 1
Patch Set 1: Code-Review-1

* running "buck build all" succeeds
* running tests fails: 

 jgit (change/81668/1)]$ buck test
 Not using buckd because watchman isn't installed.
 Parse error for build file /Users/d029788/src/git/jgit/org.eclipse.jgit.http.test/BUCK:   File "/Users/d029788/src/git/jgit/buck-out/tmp/buck_run.AidC7w/buck_python_program8529685515529725583/buck.py", line 1375, in process_with_diagnostics
    diagnostics=diagnostics)
  File "/Users/d029788/src/git/jgit/buck-out/tmp/buck_run.AidC7w/buck_python_program8529685515529725583/buck.py", line 1286, in process
    implicit_includes=self._implicit_includes)
  File "/Users/d029788/src/git/jgit/buck-out/tmp/buck_run.AidC7w/buck_python_program8529685515529725583/buck.py", line 1225, in _process_build_file
    implicit_includes=implicit_includes)
  File "/Users/d029788/src/git/jgit/buck-out/tmp/buck_run.AidC7w/buck_python_program8529685515529725583/buck.py", line 1148, in _process
    exec(code, module.__dict__)
  File "/Users/d029788/src/git/jgit/org.eclipse.jgit.http.test/BUCK", line 28, in <module>
    source_under_test = ['//org.eclipse.jgit.http.server:jgit-servlet'],
  File "/Users/d029788/src/git/jgit/buck-out/tmp/buck_run.AidC7w/buck_python_program8529685515529725583/buck.py", line 139, in  invoke
    return self.func(*args, **updated_kwargs)
TypeError: java_test() got an unexpected keyword argument 'source_under_test'

[-] PARSING BUCK FILES...FINISHED 0.0s

Patch-set: 1
Label: Code-Review=-1