Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1: Verified-1
> > 
> > Build Failed 
> > 
> > https://ci.eclipse.org/jgit/job/stable/job/jgit.gerrit-pipeline.java11/385/ : FAILURE
> 
> Not sure why this failure exactly.

Per the build log:

  Caused by: org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile: java.lang.NoSuchMethodError: 'java.lang.String org.codehaus.plexus.compiler.CompilerConfiguration.getWarnings()'

Patch-set: 1
CC: Gerrit User 44628 <44628@97ee7c02-f12f-4043-b43e-dea463d88b31>