Update patch set 4
Patch Set 4: Verified+1

> https://hudson.eclipse.org/jgit/job/jgit.gerrit/7609/ : FAILURE

Appears to be unrelated:

 Tests run: 13, Failures: 0, Errors: 1, Skipped: 12, Time elapsed: 1.65 sec <<< FAILURE! - in org.eclipse.jgit.transport.WalkEncryptionTest
org.eclipse.jgit.transport.WalkEncryptionTest$Required  Time elapsed: 0.414 sec  <<< ERROR!
 java.io.IOException: Server returned HTTP response code: 403 for URL: http://checkip.amazonaws.com

Patch-set: 4
Label: Verified=+1