Update patch set 4
Patch Set 4:

> running
 > 
 > jgit fetch --recurse-submodules origin
 > 
 > on some older state of the gerrit source code repository failed
 > with the exception:
 > 
 > java.lang.IllegalArgumentException: No enum constant
 > org.eclipse.jgit.lib.SubmoduleConfig.FetchRecurseSubmodulesMode.origin

I think it's because the --recurse-submodules parameter is setting an enum and it's taking "origin" as the value.

It works if you pass an explicit empty value, i.e.

  jgit fetch --recurse-submodules= origin

I'm not sure how to make it so --recurse-submodules on its own is handled as a boolean, but --recurse-submodules=value is still handled as enum.

Patch-set: 4
Label: Verified=0