[errorprone] PackWriter: Fix javadoc tag in new #writeIndex method
We introduced this method recently and the javadoc is not correct:

error: [InvalidInlineTag] This tag is invalid.
   @code{PackIndexWriter} instance to write the index

Change-Id: I34ed3d8b5a121fea9b8163627b46ae4a289c9462