Update patch set 2
Patch Set 2: Code-Review-1

$ buck build jgit 
hits compile errors:

warning: [options] bootstrap class path not set in conjunction with -source 1.6
/Users/d029788/src/git/jgit/org.eclipse.jgit/src/org/eclipse/jgit/lib/RebaseTodoLine.java:48: error: package org.eclipse.jgit.api.errors does not exist
import org.eclipse.jgit.api.errors.JGitInternalException;
                                  ^
/Users/d029788/src/git/jgit/org.eclipse.jgit/src/org/eclipse/jgit/lib/RebaseTodoLine.java:222: error: cannot find symbol
	private static JGitInternalException createInvalidCommentException(
	               ^
...

looks like RebaseTodoLine shouldn't use an API exception, we can't add a reference to the api module since this would yield a circular module dependency. So it seems we should fix this by using another exception here and translate that in RebaseCommand to an API exception

Patch-set: 2
Label: Code-Review=-1