Update patch set 1
Patch Set 1:

The stale file handle error that was produced while serving the pack is indeed fixed by this change. The remaining cases with a similar error message are the ones when the pack is being opened, similar to the case fixed in [1].

The stack trace looks like: 

2017-01-10 03:48:27,526] [SSH git-upload-pack '/other.git' (jenkins)] 
ERROR org.eclipse.jgit.internal.storage.file.ObjectDirectory : 
ERROR: Exception caught while accessing pack file /mirror/gerrit_seki/repos/other.git/objects/pack/pack-090c19813f464474d91193b212d3adb6d6030f93.pack,
the pack file might be corrupt
java.io.IOException: Unreadable pack index: /mirror/repos/other.git/objects/pack/pack-090c19813f464474d91193b212d3adb6d6030f93.idx
        at org.eclipse.jgit.internal.storage.file.PackIndex.open(PackIndex.java:100)
        at org.eclipse.jgit.internal.storage.file.PackFile.idx(PackFile.java:171)
        at org.eclipse.jgit.internal.storage.file.PackFile.get(PackFile.java:262)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:417)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:386)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:378)
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:152)
        at org.eclipse.jgit.lib.ObjectReader$1.open(ObjectReader.java:299)
        at org.eclipse.jgit.revwalk.RevWalk$2.next(RevWalk.java:971)
        at org.eclipse.jgit.transport.UploadPack.processHaveLines(UploadPack.java:1075)
        at org.eclipse.jgit.transport.UploadPack.negotiate(UploadPack.java:1028)
        at org.eclipse.jgit.transport.UploadPack.service(UploadPack.java:744)
        at org.eclipse.jgit.transport.UploadPack.upload(UploadPack.java:666)
        at com.google.gerrit.sshd.commands.Upload.runImpl(Upload.java:87)
        at com.google.gerrit.sshd.AbstractGitCommand.service(AbstractGitCommand.java:101)
        at com.google.gerrit.sshd.AbstractGitCommand.access$000(AbstractGitCommand.java:32)
        at com.google.gerrit.sshd.AbstractGitCommand$1.run(AbstractGitCommand.java:70)
        at com.google.gerrit.sshd.BaseCommand$TaskThunk.run(BaseCommand.java:437)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:376)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Stale file handle
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at org.eclipse.jgit.util.IO.readFully(IO.java:247)
        at org.eclipse.jgit.internal.storage.file.PackIndexV2.<init>(PackIndexV2.java:129)
        at org.eclipse.jgit.internal.storage.file.PackIndex.read(PackIndex.java:137)
        at org.eclipse.jgit.internal.storage.file.PackIndex.open(PackIndex.java:96)
        ... 25 more

We will work in a fix for this one.

[1] https://git.eclipse.org/r/#/c/45649

Patch-set: 1