Update patch set 2
Patch Set 2: I would prefer that you didn't submit this

when trying to checkout a non-existing branch jgit prints a stacktrace 

 org.eclipse.jgit.api.errors.RefNotFoundException: Ref xxx can not be resolved
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:154)
	at org.eclipse.jgit.pgm.Checkout.run(Checkout.java:77)
	at org.eclipse.jgit.pgm.TextBuiltin.execute(TextBuiltin.java:148)
	at org.eclipse.jgit.pgm.Main.execute(Main.java:191)
	at org.eclipse.jgit.pgm.Main.run(Main.java:120)
	at org.eclipse.jgit.pgm.Main.main(Main.java:94)

but native git prints

 error: pathspec 'xxx' did not match any file(s) known to git.

I think jgit should not print a stack trace here but show a proper error message since this is not a programming error but an error situation caused by an invalid input parameter provided by the user

Patch-set: 2