Update patch set 12
Patch Set 12:

(4 comments)

how can I test this ? I tried using ssh:

$ ssh -ND 8080 msohn@git.eclipse.org -p 29418

but cloning through proxy fails with refused connection, what am I doing wrong ?

$ jgit clone --ssh apache ssh://localhost:8080/jgit/jgit jgit7
Cloning into 'jgit7'...
org.eclipse.jgit.api.errors.TransportException: ssh://localhost:8080/jgit/jgit: Connection refused
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:254)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:302)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
	at org.eclipse.jgit.pgm.Clone.run(Clone.java:137)
	at org.eclipse.jgit.pgm.TextBuiltin.execute(TextBuiltin.java:264)
	at org.eclipse.jgit.pgm.Main.execute(Main.java:278)
	at org.eclipse.jgit.pgm.Main.run(Main.java:166)
	at org.eclipse.jgit.pgm.Main.main(Main.java:138)
Caused by: org.eclipse.jgit.errors.TransportException: ssh://localhost:8080/jgit/jgit: Connection refused
	at org.eclipse.jgit.transport.sshd.SshdSessionFactory.getSession(SshdSessionFactory.java:245)
	at org.eclipse.jgit.transport.sshd.SshdSessionFactory.getSession(SshdSessionFactory.java:1)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:140)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:280)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:170)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:138)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:124)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1271)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:243)
	... 7 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:301)
	at java.lang.Thread.run(Thread.java:748)

Patch-set: 12