InvalidLongObjectIdException: Use constant from StandardCharsets
Instead of hard-coding the string "US-ASCII", use the corresponding
constant from StandardCharsets.

This allows to remove the NON-NLS suppression, and the handling of
UnsupportedEncodingException which is not thrown when constructing
the String with the StandardCharsets constant.

Change-Id: I7f2285ecf554d4ca4296d25ab344c3d9226ddbc9
Signed-off-by: David Pursehouse <david.pursehouse@gmail.com>