Update patch set 1
Patch Set 1:

Let's debug together. On my linux box it still fails. See this trace with my environment,.netrc settings,proxy, ...

  ~/git/jgit> ls -l ~/.netrc ~/.gitcookies
  ls: cannot access /home/chris/.netrc: No such file or directory
  ls: cannot access /home/chris/.gitcookies: No such file or directory
  ~/git/jgit> git config -l | grep credential
  ~/git/jgit> env | grep proxy
  http_proxy=http://proxy.wdf.sap.corp:8080
  https_proxy=https://proxy.wdf.sap.corp:8080
  no_proxy=....
  ~/git/jgit> git log --oneline -1
  1b508b4 Fix push with jgit pgm failing with "unauthorized"
  ~/git/jgit> mvn -q clean install -Dmaven.test.skip=true
  Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
  ...
  Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
  ~/git/jgit> cd /tmp
  /tmp> git clone https://github.com/chalstrick/dondalfi.git
  Cloning into 'dondalfi'...
  ...
  Checking connectivity... done.
  /tmp> cd dondalfi/
  /tmp/dondalfi> echo $(date) >>a && git commit -a -m modA
  [master 5acf13e] modA
   1 file changed, 1 insertion(+)
  /tmp/dondalfi> git push origin HEAD:refs/heads/master
  Username for 'https://github.com': chalstrick
  Password for 'https://chalstrick@github.com': 
  Counting objects: 18, done.
  ...
     96fe9f3..5acf13e  HEAD -> master
  /tmp/dondalfi> echo $(date) >>a && git commit -a -m modA
  [master a5eafff] modA
   1 file changed, 1 insertion(+)
  /tmp/dondalfi> java -jar ~/git/jgit/org.eclipse.jgit.pgm/target/jgit-cli.jar push origin HEAD:refs/heads/master
  Username for https://github.com/chalstrick/dondalfi.git/info/refs?service=git-receive-pack: chalstrick
  Password: 
  Counting objects:       3
  Finding sources:        100% (3/3)
  Getting sizes:          100% (2/2)
  Compressing objects:    100% (390/390)
  Writing objects:        100% (3/3)
  org.eclipse.jgit.api.errors.TransportException: https://github.com/chalstrick/dondalfi.git: 401 Authorization Required
  	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:164)
  	at org.eclipse.jgit.pgm.Push.run(Push.java:130)
  	at org.eclipse.jgit.pgm.TextBuiltin.execute(TextBuiltin.java:199)
  	at org.eclipse.jgit.pgm.Main.execute(Main.java:223)
  	at org.eclipse.jgit.pgm.Main.run(Main.java:124)
  	at org.eclipse.jgit.pgm.Main.main(Main.java:98)
  Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/chalstrick/dondalfi.git: 401 Authorization Required
  	at org.eclipse.jgit.transport.TransportHttp$Service.openResponse(TransportHttp.java:875)
  	at org.eclipse.jgit.transport.TransportHttp$MultiRequestService.execute(TransportHttp.java:977)
  	at org.eclipse.jgit.transport.TransportHttp$Service$HttpExecuteStream.read(TransportHttp.java:903)
  	at org.eclipse.jgit.util.io.UnionInputStream.read(UnionInputStream.java:145)
  	at org.eclipse.jgit.util.IO.readFully(IO.java:247)
  	at org.eclipse.jgit.transport.PacketLineIn.readLength(PacketLineIn.java:186)
  	at org.eclipse.jgit.transport.SideBandInputStream.needDataPacket(SideBandInputStream.java:158)
  	at org.eclipse.jgit.transport.SideBandInputStream.read(SideBandInputStream.java:140)
  	at org.eclipse.jgit.util.IO.readFully(IO.java:247)
  	at org.eclipse.jgit.transport.PacketLineIn.readLength(PacketLineIn.java:186)
  	at org.eclipse.jgit.transport.PacketLineIn.readString(PacketLineIn.java:138)
  	at org.eclipse.jgit.transport.BasePackPushConnection.readStringLongTimeout(BasePackPushConnection.java:370)
  	at org.eclipse.jgit.transport.BasePackPushConnection.readStatusReport(BasePackPushConnection.java:322)
  	at org.eclipse.jgit.transport.BasePackPushConnection.doPush(BasePackPushConnection.java:202)
  	at org.eclipse.jgit.transport.TransportHttp$SmartHttpPushConnection.doPush(TransportHttp.java:807)
  	at org.eclipse.jgit.transport.BasePackPushConnection.push(BasePackPushConnection.java:154)
  	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:167)
  	at org.eclipse.jgit.transport.Transport.push(Transport.java:1250)
  	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:157)
  	... 5 more

Patch-set: 1
Label: Code-Review=0