Update patch set 1
Patch Set 1: Code-Review-1

jgit tag -d x

should fail if tag x doesn't exist with the error message

error: tag 'x' not found.

but it doesn't fail

Patch-set: 1
Label: Code-Review=-1