Revert "RevWalk: Use an incremental topological sorting algorithm"
This reverts commit ab51fe2bdb9d7f05287b686e75be7afc46d0c8f5.

Callers of RevWalk started getting IllegalArgumentExceptions like this:
1) rebaseWithCommitterEmail[default](com.google.gerrit.acceptance.api.change.RebaseIT$RebaseViaRevisionApi)
java.lang.IllegalArgumentException: 23 flags already created.
    at org.eclipse.jgit.revwalk.RevWalk.allocFlag(RevWalk.java:1419)
    at org.eclipse.jgit.revwalk.RevWalk.newFlag(RevWalk.java:1412)
    at org.eclipse.jgit.revwalk.TopoPhase.<init>(TopoPhase.java:28)
    at org.eclipse.jgit.revwalk.TopoInDegreePhase.<init>(TopoInDegreePhase.java:34)
    at org.eclipse.jgit.revwalk.TopoSortPendingGenerator.<init>(TopoSortPendingGenerator.java:35)
    at org.eclipse.jgit.revwalk.StartGenerator.next(StartGenerator.java:135)
    at org.eclipse.jgit.revwalk.RevWalk.next(RevWalk.java:678)
    at com.google.gerrit.server.git.CodeReviewCommit$CodeReviewRevWalk.next(CodeReviewCommit.java:87)
    at com.google.gerrit.server.git.MergeUtil.findUnmergedChanges(MergeUtil.java:1184)
    at com.google.gerrit.server.submit.SubmitStrategyListener.findUnmergedChanges(SubmitStrategyListener.java:78)
    at com.google.gerrit.server.submit.SubmitStrategyListener.afterUpdateRepos(SubmitStrategyListener.java:58)
    at com.google.gerrit.server.update.BatchUpdates.notifyAfterUpdateRepo(BatchUpdates.java:155)
    at com.google.gerrit.server.update.BatchUpdates.execute(BatchUpdates.java:110)
    at com.google.gerrit.server.update.SubmissionExecutor.execute(SubmissionExecutor.java:66)
    at com.google.gerrit.server.submit.MergeOp.integrateIntoHistory(MergeOp.java:1057)
    at com.google.gerrit.server.submit.MergeOp.lambda$merge$1(MergeOp.java:880)
    at com.google.gerrit.server.update.RetryableChangeAction.lambda$new$0(RetryableChangeAction.java:48)
    at com.google.gerrit.server.update.RetryableAction.lambda$new$0(RetryableAction.java:94)
    at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
    at com.github.rholder.retry.Retryer.call(Retryer.java:160)
    at com.google.gerrit.server.update.RetryHelper.executeWithTimeoutCount(RetryHelper.java:617)
    at com.google.gerrit.server.update.RetryHelper.execute(RetryHelper.java:557)
    at com.google.gerrit.server.update.RetryableAction.call(RetryableAction.java:192)
    at com.google.gerrit.server.update.RetryableChangeAction.call(RetryableChangeAction.java:84)
    at com.google.gerrit.server.submit.MergeOp.merge(MergeOp.java:889)
    at com.google.gerrit.server.submit.MergeOp.merge(MergeOp.java:757)
    at com.google.gerrit.server.restapi.change.Submit.mergeChange(Submit.java:225)
    at com.google.gerrit.server.restapi.change.Submit.apply(Submit.java:201)
    at com.google.gerrit.server.api.changes.RevisionApiImpl.submit(RevisionApiImpl.java:272)
    at com.google.gerrit.extensions.api.changes.RevisionApi.submit(RevisionApi.java:55)
    at com.google.gerrit.acceptance.api.change.RebaseIT$Base.rebaseWithCommitterEmail(RebaseIT.java:803)

Change-Id: Ie9edd86c8dbad7bf2faa82c2a0b5cc7fdbfb0ded