Update patch set 31
Patch Set 31: Abandoned

I am abandoning this change since I am no longer able to push to it.

New review started at: http://egit.eclipse.org/r/#change,4861

Error for this review was:

git push review HEAD:refs/for/master
Counting objects: 66, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (33/33), done.
Writing objects: 100% (43/43), 17.95 KiB, done.
Total 43 (delta 24), reused 0 (delta 0)
remote: Resolving deltas:  41% (10/24)
To ssh://kevinsawicki@egit.eclipse.org:29418/jgit.git
 ! [remote rejected] HEAD -> refs/for/master (change state corrupt)
error: failed to push some refs to 'ssh://kevinsawicki@egit.eclipse.org:29418/jgit.git'

Patch-set: 31