Update patch set 3
Patch Set 3:

> > org.eclipse.jgit.errors.TransportException: When trying to open a
 > > connection to http://admin@localhost:8080/a/lfsdemo/info/lfs/objects/batch
 > > the server responded with an error code. rc=401
 > 
 > I suspect it is the same issue as with GitHub over HTTP -
 > authentication is simply not implemented in JGit...
 > 
 > Can you confirm that this works with SSH?

it also failed when using ssh

I debugged the issue and found this is caused by execution of the external ssh command git-lfs-authenticate failing since it's not found on my system. I wasn't aware that we still need an external command for using built-in lfs integration. I have git lfs installed, but my version of git lfs doesn't seem to support this command :

 $ git lfs authenticate
 Error: unknown command "authenticate" for "git-lfs"
 Run 'git-lfs --help' for usage.

I have installed this version of git lfs:

 $ git lfs version
 git-lfs/2.4.2 (GitHub; darwin amd64; go 1.10.2)

Pushed another change [1] to improve propagation of exceptions up to the application.
[2] adapts EGit to this change.

[1] https://git.eclipse.org/r/#/c/124406/
[2] https://git.eclipse.org/r/#/c/124407/

Patch-set: 3