Update patch set 1
Patch Set 1:

> Patch Set 1: Code-Review+1
> 
> Thanks for the quick fix. Verifying it on Gerrit now.

I tried to build Gerrit 3.2.5 with this fix but this fails somewhere in bazel:

gerrit (stable-3.2-2020-11.notedb-refs-tags *)]$ bazelisk build release
INFO: Invocation ID: b69ce10e-bf7d-4494-8417-ff268cd2a37a
INFO: Analyzed target //:release (384 packages loaded, 9274 targets configured).
INFO: Found 1 target...
INFO: From Bundling JavaScript plugins/delete-project/delete-project-bundle.js [rollup]:
plugins/delete-project/gr-delete-repo/plugin.js → bazel-out/darwin-fastbuild/bin/plugins/delete-project/delete-project-bundle.js...
created bazel-out/darwin-fastbuild/bin/plugins/delete-project/delete-project-bundle.js in 284ms
ERROR: /Users/d029788/.cache/bazel/7bad2a2008c0528ccb0e391a73771531/external/jgit/org.eclipse.jgit/BUILD:28:8: Executing genrule @jgit//org.eclipse.jgit:jgit failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
Target //:release failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 633.389s, Critical Path: 122.43s
INFO: 706 processes: 81 internal, 568 darwin-sandbox, 1 local, 56 worker.
FAILED: Build did NOT complete successfully

Do we need to update bazel version in jgit to fix this ?

Patch-set: 1