Bazel: Add missing log4j library
In Id5376f09f0d a test with dependency on Log4J library was addedm but
the library was missed to be added to the Bazel build toolchain.

Even with added dependency the test is failing on my Laptop:

INFO: From Testing //org.eclipse.jgit.test:org_eclipse_jgit_api_SecurityManagerMissingPermissionsTest:
==================== Test output for //org.eclipse.jgit.test:org_eclipse_jgit_api_SecurityManagerMissingPermissionsTest:
JUnit4 Test Runner
.EE
Time: 0.41
There were 2 failures:
1) testCreateNewRepos_MissingPermissions(org.eclipse.jgit.api.SecurityManagerMissingPermissionsTest)
java.lang.SecurityException: GoogleTestSecurityManager is not designed to handle other security managers.
	at com.google.testing.junit.runner.util.GoogleTestSecurityManager.checkPermission(GoogleTestSecurityManager.java:58)
	at java.lang.System.setSecurityManager0(System.java:302)
	at java.lang.System.setSecurityManager(System.java:293)
	at org.eclipse.jgit.api.SecurityManagerMissingPermissionsTest.setUp(SecurityManagerMissingPermissionsTest.java:62)
2) testCreateNewRepos_MissingPermissions(org.eclipse.jgit.api.SecurityManagerMissingPermissionsTest)
java.lang.SecurityException: GoogleTestSecurityManager is not designed to handle other security managers.
	at com.google.testing.junit.runner.util.GoogleTestSecurityManager.checkPermission(GoogleTestSecurityManager.java:58)
	at java.lang.System.setSecurityManager0(System.java:302)
	at java.lang.System.setSecurityManager(System.java:293)
	at org.eclipse.jgit.api.SecurityManagerMissingPermissionsTest.tearDown(SecurityManagerMissingPermissionsTest.java:94)

FAILURES!!!
Tests run: 1,  Failures: 2

Bug: 562274
Change-Id: I873a0e09addc583455b68122f66cd3952e485f0e
Signed-off-by: David Ostrovsky <david@ostrovsky.org>