Update patch set 2
Patch Set 2: I would prefer that you didn't submit this

I get a NoClassDefFoundError here. Strange since the hamcrest bundle seems to export packeges

Patch-set: 2