Update patch set 1
Patch Set 1: Code-Review-1

(1 comment)

Please add some information about the context to the commit message. E.g.:

 dump HTTP: Avoid being confused by Content-Length of a gzipped stream

 TransportHttp sets 'Accept-Encoding: gzip' to allow the server to
 compress HTTP responses. When fetching a loose object over HTTP,
 it uses the following code to read the response:

	InputStream in = openInputStream(c);
	int len = c.getContentLength();
	return new FileStream(in, len);

 If the content is gzipped, openInputStream decompresses it and produces
 the correct content for the object. Unfortunately the Content-Length
 header contains the length of the compressed stream instead of the actual
 content length. Use a length of -1 instead --- we don't know the actual
 length.

 Loose objects are already compressed, so the gzip encoding typically
 produces a longer compressed payload. The value from the Content-Length
 is too high, producing EOFException:

  org.eclipse.jgit.errors.TransportException: Short read of block.
        at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:377)
        at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:308)
        at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:298)
        at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:245)
  Caused by: java.io.EOFException: Short read of block.
        at org.eclipse.jgit.util.IO.readFully(IO.java:249)
        at org.eclipse.jgit.transport.PacketLineIn.readLength(PacketLineIn.java:225)
        at org.eclipse.jgit.transport.PacketLineIn.readString(PacketLineIn.java:155)
        at org.eclipse.jgit.transport.PacketLineIn.readACK(PacketLineIn.java:119)
        at org.eclipse.jgit.transport.BasePackFetchConnection.negotiate(BasePackFetchConnection.java:667)
        at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:363)

Patch-set: 1
Label: Code-Review=-1