Update patch set 15
Patch Set 15:

> Patch Set 14: Code-Review-1
> 
> JGit bot says one test fails, which I can reproduce locally using "bazel test ...". Could you take a look?
> 
> 1) validateUnadvertisedTipWithBitmaps(org.eclipse.jgit.transport.ReachableCommitTipRequestValidatorTest)
> org.eclipse.jgit.transport.WantNotValidException: want 74906d8d9a82254ae624e90adca9d611a5fc7b79 not valid

The test has two commits with a common parent as a started. The second starter was ignored by the walk before even calling to the filter.

I think it is due to the TOPO order (the second starter has a visited parent). I think it is correct to reset the walk. The visited state is stored in the filter's bitmap.

Patch-set: 15
Reviewer: Gerrit User 201156 <201156@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Verified=0