Implement SystemReader.isAndroid()
instead of catching a NoClassDefFoundError in
internal.storage.file.GC.getPID().

This is done to get GC.getPID() to work on Android, where
ProcessHandle.pid() is not supported.

Change-Id: Ia70affff96a682eb275dde1e5d14dccabf8db593