Update patch set 35
Patch Set 35:

org.eclipse.jgit.api.AddCommandTest.testBadCleanFilter

Failing for the past 1 build (Since Failed#8709 )
Took 29 ms.
Error Message

expected:<127> but was:<0>
Stacktrace

java.lang.AssertionError: expected:<127> but was:<0>
	at org.eclipse.jgit.api.AddCommandTest.testBadCleanFilter(AddCommandTest.java:256)


That hudson failure seems unrelated to me?

Patch-set: 35
Label: Verified=0