Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> on MacOS the javadoc generation fails with this error:
> 
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.3.1:jar (default) on project org.eclipse.jgit: MavenReportException: Error while generating Javadoc:
> [ERROR] Exit code: 1 - /Users/xxx/src/git/jgit/org.eclipse.jgit/src/org/eclipse/jgit/util/IO.java:33: error: class IO clashes with package of same name
> [ERROR] public class IO {
> [ERROR]        ^
> Any idea how to fix this without renaming IO.java which would be a breaking change ?

Is mac file system case insensitive?
Which compiler is used, might be there is a new version available? Looks like a bug...

Patch-set: 3