DefaultTypedConfigGetter: Box values to avoid infinite recursion
Errorprone says:

DefaultTypedConfigGetter.java:176:

error: [InfiniteRecursion] This method always recurses, and will cause
		a StackOverflowError return getLong(config, section,
		subsection, name, defaultValue);

[1] introduced new getters with boxed types to return a null when the
config is not set. The getters of unboxed types should call to the
boxed version, but, as the values are not explicitely boxed, they
are calling to themselves.

[1] https://gerrithub.io/c/eclipse-jgit/jgit/+/1207895

Change-Id: Ied45a199c8ef905e3774a17a04d91a656aa0e42b