Update patch set 6
Patch Set 6:

> I hope that's good enough for Jonathan. Might be a while until we get to the top of this series...
> 
> If it's really urgent, I _could_ do it at the bottom, but it'll take me a few hours, and I'll have to re-test maven & bazel builds on each commit where I have to change things. I don't think I could get to it this week anyway.

I can revert locally in the meantime, so there's no rush.

> What problems does this cause actually?

We're using Apache SSHD 2.1.0 here. The tests fail to build:

 org.eclipse.jgit.junit/java/org/eclipse/jgit/junit/ssh/SshTestGitServer.java:193: error: constructor AbstractCommandSupport in class AbstractCommandSupport cannot be applied to given types;
                        super(command, executorService, false);
                        ^
  required: String,CloseableExecutorService
  found:    String,ExecutorService,boolean
  reason: actual and formal argument lists differ in length

Patch-set: 6