Update patch set 2
Patch Set 2: Code-Review+1

looks good

did you also consider specialised config classes ? E.g. RemoteConfig throws IllegalArgumentException if an illegal refspec was configured, e.g. missing colon in the fetch refspec throws an IllegalArgumentException in RemoteConfig line 198

[remote "origin"]
	fetch = +refs/heads/*refs/remotes/origin/*

java.lang.IllegalArgumentException: Invalid wildcards +refs/heads/*refs/remotes/origin/*
	at org.eclipse.jgit.transport.RefSpec.<init>(RefSpec.java:196)
	at org.eclipse.jgit.transport.RefSpec.<init>(RefSpec.java:226)
	at org.eclipse.jgit.transport.RemoteConfig.<init>(RemoteConfig.java:198)
	at org.eclipse.egit.gitflow.GitFlowConfig.getDefaultRemoteConfig(GitFlowConfig.java:251)
	at org.eclipse.egit.gitflow.GitFlowConfig.hasDefaultRemote(GitFlowConfig.java:262)
	at org.eclipse.egit.gitflow.ui.internal.properties.RepositoryPropertyTester.test(RepositoryPropertyTester.java:74)
	at org.eclipse.core.internal.expressions.Property.test(Property.java:58)
...

Patch-set: 2