Disable BOUNDARY and TOPO sort for unshallow fetches
During the navigation of commits reachable by two or more paths, the
combination of TopoSortGenerator and BoundaryGenerator was interfering
with the normal DepthGenerator of unshallow requests.

Example use-case:

     [unshallow-branch]
         |
         v
c1 <--- c2 <--- c3 <--- c4 <--- c5 <--- c6 <-[main-branch]
                ^
                |
         [stable-branch]

The commit c2 is UNSHALLOW and is reachable by both [main-branch] and
[stable-branch], therefore, is reachable twice. The DepthGenerator keeps
some reference counting on the RevObject to keep track of the commit
depth navigation of unshallow requests.

Before this change, the unshallow requests were combined with
BoundaryGenerator and TopoSortGenerator, which were never adapted to
support that scenario [1], therefore, they were dropping the
uninteresting commit c2, and therefore the associated hierarchy path was
lost and not returned as part of the navigation.

From a client's perspective, this was visible with the 'unshallow'
command failing with:

error: Could not read (SHA1 of c1) fatal: Failed to traverse parents of
commit (SHA1 of c2)

With this fix, the PackWriter does not request the BOUNDARY and TOPO
sorting and just relying on the DepthGenerator, which works as expected
and continues the navigation, returning all the commits needed to serve
the client.

[1] https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1320

Bug: jgit-182
Change-Id: Iacf3d06fd021b7548a1dd4ecc27151d0b20e4b10
Signed-off-by: Luca Milanesio <luca.milanesio@gmail.com>