Update patch set 9
Patch Set 9:

thanks, this works fine on Java 10,

On Java 11 I hit this error

ERROR: org.eclipse.jgit/BUILD:16:1: Building org.eclipse.jgit/libjgit-class.jar (822 source files) failed (Exit 1)
error: module not found: java.xml.bind

though I think this is not caused by bazel or bazel configuration but needs changes in WalkEncryption which is using classes from this package which is no longer part of JDK 11

Patch-set: 9
Reviewer: Gerrit User 4 <4@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Verified=0