Improve handling of usernames with special characters (e.g. backslashes)
When using an URIish to establish a http connection the transport
implementation TransportHttp uses URIish#toString and passes the output to
the java.net.URL constructor.

For special characters in the authority part of the URL the constructor raises
an IllegalArgumentException. Concrete backtrace:

java.lang.IllegalArgumentException: Illegal character found in user-info: '\'
	at java.base/java.net.URLStreamHandler.setURL(URLStreamHandler.java:527)
	at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:326)
	at java.base/java.net.URL.<init>(URL.java:801)
Caused: java.net.MalformedURLException: Illegal character found in user-info: '\'
	at java.base/java.net.URL.<init>(URL.java:806)
	at java.base/java.net.URL.<init>(URL.java:654)
	at java.base/java.net.URL.<init>(URL.java:590)
	at org.eclipse.jgit.transport.TransportHttp.toURL(TransportHttp.java:304)
	at org.eclipse.jgit.transport.TransportHttp.setURI(TransportHttp.java:319)

RFC2396 defines this construction:

userinfo      = *( unreserved | escaped |
                   ";" | ":" | "&" | "=" | "+" | "$" | "," )
unreserved    = alphanum | mark
mark          = "-" | "_" | "." | "!" | "~" | "*" | "'" |
                "(" | ")"
escaped       = "%" hex hex
hex           = digit | "A" | "B" | "C" | "D" | "E" | "F" |
                        "a" | "b" | "c" | "d" | "e" | "f"
alphanum      = alpha | digit
alpha         = lowalpha | upalpha
lowalpha      = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" |
                "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" |
                "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
upalpha       = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" |
                "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" |
                "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
digit         = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |
                "8" | "9"

So the exception is in line with the RFC definition. The suggested
implementation change inverts the approach by not using a list of reserved
characters, but using the definition of the unreserved characters and
use these as validity list.

Change-Id: Ic92d35582a056f2aea0cb016482b4e91cd262037