Update patch set 2
Patch Set 2: Code-Review-1

(1 comment)

I tried creating a signed tag and this fails with this exception:

$ jgit tag -s -m v0.1 v0.1
org.eclipse.jgit.api.errors.JGitInternalException: unknown object in stream: 12
	at org.eclipse.jgit.gpg.bc.internal.BouncyCastleGpgSigner.signObject(BouncyCastleGpgSigner.java:177)
	at org.eclipse.jgit.api.TagCommand.call(TagCommand.java:140)
	at org.eclipse.jgit.pgm.Tag.run(Tag.java:102)
	at org.eclipse.jgit.pgm.TextBuiltin.execute(TextBuiltin.java:235)
	at org.eclipse.jgit.pgm.Main.execute(Main.java:245)
	at org.eclipse.jgit.pgm.Main.run(Main.java:133)
	at org.eclipse.jgit.pgm.Main.main(Main.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.io.IOException: unknown object in stream: 12
	at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
	at org.bouncycastle.openpgp.PGPPublicKeyRingCollection.<init>(Unknown Source)
	at org.eclipse.jgit.gpg.bc.internal.BouncyCastleGpgKeyLocator.findPublicKeyInPubring(BouncyCastleGpgKeyLocator.java:564)
	at org.eclipse.jgit.gpg.bc.internal.BouncyCastleGpgKeyLocator.findSecretKey(BouncyCastleGpgKeyLocator.java:364)
	at org.eclipse.jgit.gpg.bc.internal.BouncyCastleGpgSigner.locateSigningKey(BouncyCastleGpgSigner.java:97)
	at org.eclipse.jgit.gpg.bc.internal.BouncyCastleGpgSigner.signObject(BouncyCastleGpgSigner.java:113)
	... 14 more

doing the same using c git succeeds.

command line help for the jgit tag command fails due to a missing text:

$ jgit tag -h

jgit tag [name] [object] [--annotate (-a)] [--help (-h)] [--local-user (-u) <GPG key ID>] [--no-sign] [--sign (-s)] [--ssh [JSCH | APACHE]] [-d] [-f] [-m message]

java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key usage_tagAnnotated
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at org.kohsuke.args4j.CmdLineParser.localize(CmdLineParser.java:366)
	at org.kohsuke.args4j.CmdLineParser.printOption(CmdLineParser.java:341)
	at org.kohsuke.args4j.CmdLineParser.printUsage(CmdLineParser.java:303)
	at org.kohsuke.args4j.CmdLineParser.printUsage(CmdLineParser.java:273)
	at org.eclipse.jgit.pgm.TextBuiltin.printUsage(TextBuiltin.java:314)
	at org.eclipse.jgit.pgm.TextBuiltin.parseArguments(TextBuiltin.java:263)
	at org.eclipse.jgit.pgm.TextBuiltin.execute(TextBuiltin.java:217)
	at org.eclipse.jgit.pgm.Main.execute(Main.java:245)
	at org.eclipse.jgit.pgm.Main.run(Main.java:133)
	at org.eclipse.jgit.pgm.Main.main(Main.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

Patch-set: 2
Reviewer: Gerrit User 4 <4@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Code-Review=-1