Update patch set 3
Patch Set 3:

(1 comment)

> I tried creating a signed tag and this fails with this exception:
> 
> $ jgit tag -s -m v0.1 v0.1
> org.eclipse.jgit.api.errors.JGitInternalException: unknown object in stream: 12

That must be a problem with your GPG setup. It fails reading ~/.gnupg/pubring.gpg. Maybe a version problem? Try signing a commit. I would expect that to fail in the same way.

If so, there's some adaptation in the BouncyCastleGpgKeyLocator needed, but that's unrelated to signing tags. What GPG version are you using? What's the content of the pubring.gpg file? Maybe it's a version problem, and BC cannot read the pubring.gpg of your GPG version?

I'm not fond of using BouncyCastle for GPG. It's just yet another source of incompatibilities (beyond the differences between JGit and C git). Might have been better to just shell out to a gpg executable.

In any case the above command works for me; the resulting tag is signed and can be verified by C git:

  ~/tmp/tagtest $ ~/tmp/jgit511.sh tag -s -m v0.1 v0.1
  ~/tmp/tagtest $ git tag -l
  annotated
  authortag
  gannotated
  glightweight
  jsignedtag
  lightweight
  signedtag
  v0.1
  ~/tmp/tagtest $ git tag -v v0.1
  object 08d9f18b4155fd98442359384f795cacac492fc6
  type commit
  tag v0.1
  tagger A U Thor <a.u.thor@example.org> 1607328916 +0100
  
  v0.1
  gpg: Signature made Mon Dec  7 09:15:16 2020 CET
  gpg:                using RSA key 082D002FE303507C427A23F34459E98A0A6890FB
  gpg:                issuer "a.u.thor@example.org"
  gpg: Good signature from "A U Thor <a.u.thor@example.org>" [ultimate]
  ~/tmp/tagtest $
  ~/tmp/tagtest $ git cat-file -p `cat .git/refs/tags/v0.1`
  object 08d9f18b4155fd98442359384f795cacac492fc6
  type commit
  tag v0.1
  tagger A U Thor <a.u.thor@example.org> 1607328916 +0100
  
  v0.1
  -----BEGIN PGP SIGNATURE-----
  Version: BCPG v1.65
  
  iQFJBAABCAAzBQJfzeSUFiEECC0AL+MDUHxCeiPzRFnpigpokPsVHGEudS50aG9y
  QGV4YW1wbGUub3JnAAoJEERZ6YoKaJD7QYkIAK8Om+/QugVqfdKZlMrfcQcrXwgZ
  KiGFd6y+tZADLh7uItTT4gMoGil3NuVtxQSrGPyb0cBsjnFsSkXC/lVPr6FcGZ2r
  ji/uAABEtJjWfwO7VpIVRiftJgQAHAPHjRH5fKQeLtdXg7yWsxaHrQioiVPCpoTE
  5+XO9hJkkbN+EBJ2Sl+oilaxI8joMrXar7k7X8sL0amO53dE0MyuOLO1EK0Tqc2G
  /9qKWlhhiWXJ8IPIE91/4mziXm3Y2pMxmIdH0XAHcOK+fZ0ExiBu+/nMQn8NHnh8
  3tevZs4kvXl9jni2vH+IQA2/D2WZ9yz9KFp7ZxqAcsejZfc7oCjIklASGEI=
  =jKTg
  -----END PGP SIGNATURE-----
  ~/tmp/tagtest $
  ~/tmp/tagtest $ git tag -s -m v0.1-git v0.1-git
  ~/tmp/tagtest $ git tag -v v0.1-git
  object 08d9f18b4155fd98442359384f795cacac492fc6
  type commit
  tag v0.1-git
  tagger A U Thor <a.u.thor@example.org> 1607329013 +0100
  
  v0.1-git
  gpg: Signature made Mon Dec  7 09:16:53 2020 CET
  gpg:                using RSA key 082D002FE303507C427A23F34459E98A0A6890FB
  gpg:                issuer "a.u.thor@example.org"
  gpg: Good signature from "A U Thor <a.u.thor@example.org>" [ultimate]
  ~/tmp/tagtest $
  ~/tmp/tagtest $ git cat-file -p `cat .git/refs/tags/v0.1-git`
  object 08d9f18b4155fd98442359384f795cacac492fc6
  type commit
  tag v0.1-git
  tagger A U Thor <a.u.thor@example.org> 1607329013 +0100
  
  v0.1-git
  -----BEGIN PGP SIGNATURE-----
  
  iQFJBAABCgAzFiEECC0AL+MDUHxCeiPzRFnpigpokPsFAl/N5PUVHGEudS50aG9y
  QGV4YW1wbGUub3JnAAoJEERZ6YoKaJD7uP8H/3ABrT5jpZ6LGPnnpqcBOebtxgEf
  +wEWZTrkRGI6HrgVB76kPPOJa8xFqQF8ZAnscn8G+JdviCCDQeuEx8AZltr87pLM
  +Zk8QYkIJAO7mJBFTWQ+8Cr0LYJ0nEGHODQ8zrJyno//HLpKzeQG657zexMmiAdB
  a8etlSCwtJ4F9WgoOaMN0ycRqNLFCTxv0X54NGpHS4Ar3sAO+0lVB3T5deaV8TfA
  alAJ9GNlg1/0QmDZ6be47uEMG2r/agaiPixytwX3q5zIajh09fitl6snG6UGCRTM
  96DM0BUd4R600mBh0EvnEt+0FEIy8BL2jOnvFHlSqlfst321Do8QGR7KMzA=
  =Z4xg
  -----END PGP SIGNATURE-----
  ~/tmp/tagtest $

> command line help for the jgit tag command fails due to a missing text:

Fixed.

Patch-set: 3