Update patch set 3
Patch Set 3:

> Build Failed

Hmmm. Actually, it's caused by

  [INFO] Compiling 22 source files to /jobs/genie.jgit/jgit.gerrit/workspace/org.eclipse.jgit.pgm.test/target/test-classes
/jobs/genie.jgit/jgit.gerrit/workspace/org.eclipse.jgit.test/src/org/eclipse/jgit/events/ChangeRecorder.java:46: error: package org.junit does not exist
  import static org.junit.Assert.assertArrayEquals;

I have _no_ clue why this occurs. Doesn't occur in Eclipse. Maven problem? (org.junit and org.hamcrest are dependencies with scope "test" in pom.xml. Could that be the reason??)

Patch-set: 3
Label: Verified=0