Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > https://ci.eclipse.org/jgit/job/stable/job/jgit.gerrit-pipeline/5366/ : FAILURE
> 
> This fails because the jarsigner version is too old. The version bump to 1.3.1 from I34319d7006be13534497499e97536a8278906b1f and Ia7c1c9f443793ce476acd6ddfe521ea488a1a60b needs to be backported to older branches.

Thanks for the heads up @Thomas.
I tried to cherry-pick those two commits to 5.9, but I am afraid I am not powerful enough.

```
➜  jgit git:(50cb51446) ✗ git push origin HEAD:refs/for/stable-5.9
Enumerating objects: 29, done.
Counting objects: 100% (29/29), done.
Delta compression using up to 12 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (17/17), 2.25 KiB | 1.12 MiB/s, done.
Total 17 (delta 9), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (9/9)
remote: Processing changes: refs: 1, done
remote: commit 590bc81: ----------
remote: commit 590bc81: Reviewing commit: 590bc81b
remote: commit 590bc81: Authored by: Thomas Wolf <thomas.wolf@paranor.ch>
remote: commit 590bc81:
remote: commit 590bc81: Reviewing commit: 590bc81b5477d529d1be0e32f0da8a4fb2aa5782
remote: commit 590bc81: Authored by: Thomas Wolf <thomas.wolf@paranor.ch>
remote: commit 590bc81: Eclipse user 'twolf'(author) is a committer on the project.
remote: commit 590bc81: Eclipse user 'abaronehy3'(committer) is not a committer on the project.
remote: commit 590bc81: Eclipse user 'abaronehy3'(committer) has a current Eclipse Contributor Agreement (ECA) on file.
remote: commit 590bc81: You are not a project committer.
remote: commit 590bc81: Only project committers can push on behalf of others.
remote: commit 590bc81:
remote: commit 590bc81: Please see http://wiki.eclipse.org/ECA
To ssh://git.eclipse.org:29418/jgit/jgit
 ! [remote rejected]     HEAD -> refs/for/stable-5.9 (commit 590bc81: You must be a committer to push on behalf of others.)
error: failed to push some refs to 'ssh://git.eclipse.org:29418/jgit/jgit'
```

Any change you could do those cherry-picks for me when you have a moment? 🙏

Patch-set: 1