Fix after_open config unit tests to work with bazel test
The change I1db6fcf414b added couple of tests which were failing with
error [1] with "bazel test //...". This was not caught because we
don't have CI running with bazel. Fix bazel build file so that these
errors are no longer thrown when run with bazel.

[1] error: cannot find symbol FileRepositoryBuilderTest

Bug: 581816
Signed-off-by: Prudhvi Akhil Alahari <quic_prudhvi@quicinc.com>
Change-Id: I1e57111662825f5f14f373bc4f8d24cce1fec0b8