Update patch set 2
Patch Set 2:

The test failure is again unrelated to my change:
java.io.IOException: Writing of 'tester-1445391864422.jgit/' failed: 403 Forbidden
	at org.eclipse.jgit.transport.AmazonS3.error(AmazonS3.java:527)

The original change was split into 3: 
1) https://git.eclipse.org/r/#/c/58526/ "Push control of time into MockSystemReader"
2) This current change
3) Follow up that exposes control of GC parameters through PackConfig.

Patch-set: 2
Label: Verified=0