Update patch set 1
Patch Set 1:

(1 comment)

this breaks the gerrit build

gerrit-server/src/main/java/com/google/gerrit/server/patch/PatchListLoader.java:436: error: no suitable method found for formatMerge(org.eclipse.jgit.util.TemporaryBuffer,org.eclipse.jgit.merge.MergeResult<capture#1 of ? extends org.eclipse.jgit.diff.Sequence>,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
            fmt.formatMerge(buf, p, "BASE", oursName, theirsName, UTF_8.name());
               ^
    method org.eclipse.jgit.merge.MergeFormatter.formatMerge(java.io.OutputStream,org.eclipse.jgit.merge.MergeResult<org.eclipse.jgit.diff.RawText>,java.lang.String,java.lang.String,java.lang.String,java.lang.String) is not applicable
      (actual argument org.eclipse.jgit.merge.MergeResult<capture#1 of ? extends org.eclipse.jgit.diff.Sequence> cannot be converted to org.eclipse.jgit.merge.MergeResult<org.eclipse.jgit.diff.RawText> by method invocation conversion)
    method org.eclipse.jgit.merge.MergeFormatter.formatMerge(java.io.OutputStream,org.eclipse.jgit.merge.MergeResult<org.eclipse.jgit.diff.RawText>,java.util.List<java.lang.String>,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)

Patch-set: 1
Reviewer: Gerrit User 4 <4@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Verified=0