Update patch set 5
Patch Set 5:

The failure seems to be caused by Hudson, not my code. I don't know how to make Hudson retry, though.

ERROR: Problem fetching from origin / origin - could be unavailable. Continuing anyway
hudson.plugins.git.GitException: Error performing command: git fetch -t git://git.eclipse.org/gitroot/jgit/jgit.git refs/changes/81/24681/5

Patch-set: 5
Label: Verified=0