PullCommandTest: Unused variable
```
org.eclipse.jgit.test/tst/org/eclipse/jgit/api/PullCommandTest.java:191: error: [UnusedVariable] This assignment to the local variable 'res' is never read.
                res = target.pull().call();
                    ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
```

Change-Id: I54f5caa01e316cab2f26437e117573e96a6a6964