Update patch set 2
Patch Set 2:

$ mvn clean install
[...]
 [INFO] BUILD SUCCESS
 [INFO] ------------------------------------------------------------------------
 [INFO] Total time: 3:34.113s
 [INFO] Finished at: Mon Apr 29 17:11:55 PDT 2013
 [INFO] Final Memory: 20M/178M
 [INFO] ------------------------------------------------------------------------
 $ mvn -e -f org.eclipse.jgit.packaging/pom.xml clean install
[...]
 [INFO] Computing target platform for MavenProject: org.eclipse.jgit.feature:org.eclipse.jgit.pgm:3.0.0-SNAPSHOT @ /usr/local/google/home/jrn/src/jgit/org.eclipse.jgit.packaging/org.eclipse.jgit.pgm.feature/pom.xml
 [INFO] Resolving dependencies of MavenProject: org.eclipse.jgit.feature:org.eclipse.jgit.pgm:3.0.0-SNAPSHOT @ /usr/local/google/home/jrn/src/jgit/org.eclipse.jgit.packaging/org.eclipse.jgit.pgm.feature/pom.xml
 [INFO] Cannot complete the request.  Generating details.
 [INFO] Cannot complete the request.  Generating details.
 [INFO] {osgi.ws=gtk, osgi.os=linux, osgi.arch=x86, org.eclipse.update.install.features=true}
 [ERROR] Cannot resolve project dependencies:
 [ERROR]   Software being installed: org.eclipse.jgit.pgm.feature.group 3.0.0.qualifier
 [ERROR]   Missing requirement: org.eclipse.jgit.pgm.feature.group 3.0.0.qualifier requires 'org.eclipse.jgit.archive 0.0.0' but it could not be found
 [ERROR] 
 [ERROR] Internal error: java.lang.RuntimeException: "No solution found because the problem is unsatisfiable.": ["Unable to satisfy dependency from org.apache.commons.compress 1.4.1 to package org.tukaani.xz 0.0.0.", "Unable to satisfy dependency from org.eclipse.jgit.pgm 3.0.0.201304291708 to package org.eclipse.jgit.archive [3.0.0,3.1.0).", "Unable to satisfy dependency from org.eclipse.jgit.pgm.feature.group 3.0.0.qualifier to org.eclipse.jgit.archive 0.0.0.", "No solution found because the problem is unsatisfiable."] -> [Help 1]
 org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: "No solution found because the problem is unsatisfiable.": ["Unable to satisfy dependency from org.apache.commons.compress 1.4.1 to package org.tukaani.xz 0.0.0.", "Unable to satisfy dependency from org.eclipse.jgit.pgm 3.0.0.201304291708 to package org.eclipse.jgit.archive [3.0.0,3.1.0).", "Unable to satisfy dependency from org.eclipse.jgit.pgm.feature.group 3.0.0.qualifier to org.eclipse.jgit.archive 0.0.0.", "No solution found because the problem is unsatisfiable."]
         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
         at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:616)
         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
 Caused by: java.lang.RuntimeException: "No solution found because the problem is unsatisfiable.": ["Unable to satisfy dependency from org.apache.commons.compress 1.4.1 to package org.tukaani.xz 0.0.0.", "Unable to satisfy dependency from org.eclipse.jgit.pgm 3.0.0.201304291708 to package org.eclipse.jgit.archive [3.0.0,3.1.0).", "Unable to satisfy dependency from org.eclipse.jgit.pgm.feature.group 3.0.0.qualifier to org.eclipse.jgit.archive 0.0.0.", "No solution found because the problem is unsatisfiable."]
         at org.eclipse.tycho.p2.resolver.AbstractResolutionStrategy.newResolutionException(AbstractResolutionStrategy.java:81)
         at org.eclipse.tycho.p2.resolver.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:88)
         at org.eclipse.tycho.p2.resolver.AbstractResolutionStrategy.resolve(AbstractResolutionStrategy.java:58)
         at org.eclipse.tycho.p2.impl.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:122)
         at org.eclipse.tycho.p2.impl.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:78)
         at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.doResolvePlatform(P2TargetPlatformResolver.java:373)
         at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.resolveDependencies(P2TargetPlatformResolver.java:350)
         at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.resolveProject(DefaultTychoDependencyResolver.java:109)
         at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:82)
         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
         ... 11 more
 [ERROR] 
 [ERROR] 
 [ERROR] For more information about the errors and possible solutions, please read the following articles:
 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
 $

Patch-set: 2