Update patch set 1
Patch Set 1:

> https://ci-staging.eclipse.org/jgit/job/jgit/2108/consoleFull fails
 > due to
 > 
 > [INFO] Running org.eclipse.jgit.ant.tasks.GitCloneTaskTest
 > [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time
 > elapsed: 0.082 s <<< FAILURE! - in org.eclipse.jgit.ant.tasks.GitCloneTaskTest
 > [ERROR] initializationError(org.eclipse.jgit.ant.tasks.GitCloneTaskTest)
 >  Time elapsed: 0.003 s  <<< ERROR!
 > java.lang.SecurityException: class "org.eclipse.jgit.ant.tasks.GitCloneTask"'s
 > signer information does not match signer information of other
 > classes in the same package
 > 
 > ???
 > 
 > And https://ci.eclipse.org/jgit/job/jgit/2149/#showFailuresLink
 > fails because of that BatchRefUpdateTest. Maybe it's time to
 > disable that test?
 > 
 > These build failures prevent deploying JGit 5.5.0-SNAPSHOT, which
 > prevents building EGit 5.5.0-SNAPSHOT.

maybe that's again caused by the shaky TimeStamp provider used by the signing service ? 

See yesterday's issues with release build https://bugs.eclipse.org/bugs/show_bug.cgi?id=548204

Patch-set: 1