Update patch set 1
Patch Set 1:

Three tests are still failing with this change:

  //org.eclipse.jgit.http.test:http                         FAILED in 184.2s
  //org.eclipse.jgit.lfs.server.test:lfs_server             FAILED in 10.9s
  //org.eclipse.jgit.test:org_eclipse_jgit_lib_ConfigTest   FAILED in 2.9s

ConfigTest failure is:

  1) testCommitTemplatePathInHomeDirecory(org.eclipse.jgit.lib.ConfigTest)
  java.io.IOException: Read-only file system
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createTempFile(File.java:2129)
	at org.eclipse.jgit.lib.ConfigTest.testCommitTemplatePathInHomeDirecory(ConfigTest.java:1560)

Other tests seem missing some http-dependencies:

  1) testKnownContent(org.eclipse.jgit.lfs.server.fs.CheckoutTest)
  java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletMapping

Patch-set: 1