Update patch set 4
Patch Set 4:

The occurrence of MissingObjectException dropped in our repositories from hundreds to a few dozens a day. Thanks for the fixes. 
We still have a case; however, where the users are unable to clone or pull from the repository because of a similar issue: 

[SSH git-upload-pack '/project' (user)] ERROR com.google.gerrit.sshd.BaseCommand : Internal server error (user account 123) during git-upload-pack '/project'
org.eclipse.jgit.errors.PackProtocolException: want 63c1c82b24e42efa2d83ae36202af77c7387a119 not valid
at org.eclipse.jgit.transport.UploadPack.parseWants(UploadPack.java:1190)
at org.eclipse.jgit.transport.UploadPack.processHaveLines(UploadPack.java:1063)
at org.eclipse.jgit.transport.UploadPack.negotiate(UploadPack.java:1043)
at org.eclipse.jgit.transport.UploadPack.service(UploadPack.java:744)
at org.eclipse.jgit.transport.UploadPack.upload(UploadPack.java:666)
at com.google.gerrit.sshd.commands.Upload.runImpl(Upload.java:87)
at com.google.gerrit.sshd.AbstractGitCommand.service(AbstractGitCommand.java:101)
at com.google.gerrit.sshd.AbstractGitCommand.access$000(AbstractGitCommand.java:32)
at com.google.gerrit.sshd.AbstractGitCommand$1.run(AbstractGitCommand.java:70)
at com.google.gerrit.sshd.BaseCommand$TaskThunk.run(BaseCommand.java:437)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:396)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 63c1c82b24e42efa2d83ae36202af77c7387a119
at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:156)
at org.eclipse.jgit.lib.ObjectReader$1.open(ObjectReader.java:299)
at org.eclipse.jgit.revwalk.RevWalk$2.next(RevWalk.java:971)
at org.eclipse.jgit.transport.UploadPack.parseWants(UploadPack.java:1176)
... 17 more

Running JGit GC fixes this error but it comes again after a few minutes. Checking in the repository, the "missing" object is present and most of the times is a commit even if we have also seen trees.

Any hints how to troubleshoot this? I want to understand why is GC fixing temporarily the repository but it "corrupts" again later and also an idea of the causes and how to fix this problem in a more permanent basis. I have to say that from the thousands of repositories in our Gerrit instance, only a handful of them show this behavior. Thanks.

Patch-set: 4