Update patch set 3
Patch Set 3:

I have deployed to prod the latest stable-5.1 with the extra logging on the full exception that causes a packfile is removed from the list.

As a surprise I found out two things:
a) The packfile was previously flagged as invalid, but there is no trace in the log of earlier errors
b) The packfile removed from the list was *exactly* the one re-created by GC. The result is quite nasty, because the only valid packfile in "good shape" and active after GC is the one that is getting removed from the in-memory cache.

See the exception below:

[2019-02-18 21:36:37,636] [pool-28-thread-8] WARN  org.eclipse.jgit.internal.storage.file.ObjectDirectory : Packfile /var/gerrit/git/All-Users.git/objects/pack/pack-71b0129d6dc814b0debdce685ed2d37544245c37.pack is corrupted
org.eclipse.jgit.errors.PackInvalidException: Pack file invalid: /var/gerrit/git/All-Users.git/objects/pack/pack-71b0129d6dc814b0debdce685ed2d37544245c37.pack
        at org.eclipse.jgit.internal.storage.file.PackFile.doOpen(PackFile.java:641)
        at org.eclipse.jgit.internal.storage.file.PackFile.beginWindowCache(PackFile.java:625)
        at org.eclipse.jgit.internal.storage.file.WindowCache.load(WindowCache.java:295)
        at org.eclipse.jgit.internal.storage.file.WindowCache.getOrLoad(WindowCache.java:379)
        at org.eclipse.jgit.internal.storage.file.WindowCache.get(WindowCache.java:184)
        at org.eclipse.jgit.internal.storage.file.WindowCursor.pin(WindowCursor.java:360)
        at org.eclipse.jgit.internal.storage.file.WindowCursor.copy(WindowCursor.java:259)
        at org.eclipse.jgit.internal.storage.file.PackFile.readFully(PackFile.java:601)
        at org.eclipse.jgit.internal.storage.file.PackFile.load(PackFile.java:773)
        at org.eclipse.jgit.internal.storage.file.PackFile.get(PackFile.java:285)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:491)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:449)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:440)
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:165)
        at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:176)
        at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:146)
        at org.eclipse.jgit.lib.Repository.open(Repository.java:349)

Any ideas?

Patch-set: 3