Implement SystemReader.isAndroid()
instead of catching a NoClassDefFoundError.

As advised by Matthias Sohn.

Change-Id: Ia70affff96a682eb275dde1e5d14dccabf8db593