Update patch set 1
Patch Set 1:

> Maven failure seems to be related:
 > 
 > [ERROR] Tests run: 30, Failures: 0, Errors: 1, Skipped: 0, Time
 > elapsed: 9.749 s <<< FAILURE!
 > - in org.eclipse.jgit.pgm.ArchiveTest
 > [ERROR] testTxzExtension(org.eclipse.jgit.pgm.ArchiveTest)  Time
 > elapsed: 0.031 s  <<< ERROR!
 > java.lang.NoClassDefFoundError: org/tukaani/xz/FilterOptions
 > at org.eclipse.jgit.pgm.ArchiveTest.testTxzExtension(ArchiveTest.java:276)
 > Caused by: java.lang.ClassNotFoundException: org.tukaani.xz.FilterOptions
 > at org.eclipse.jgit.pgm.ArchiveTest.testTxzExtension(ArchiveTest.java:276)
 > 
 > Can it be, that new version should be uploaded first in Eclipse
 > Foundation's own Maven repository?

It also fails locally on the maven build.  I think there's some other configuration that needs to be updated but I wasn't able to figure out exactly what/where.  For example there's a manifest file that specifies the xz version, and updating that didn't help.

FWIW the jar file for the old and new versions both include that FilterOptions class.

Patch-set: 1
Label: Verified=0