InvalidRefNameException: Handle the exception when Checkout is called with an invalid ref
Currently, the checkout command is throwing InvalidRefNameException
which is not being caught. This results in an exception visible
to the user. This fix catches the exception and shows the user a
meaningful message of what went wrong

Bug: jgit-146
Change-Id: Iadb0feecba955912161444239a36a2fad201dc34