Update patch set 1
Patch Set 1:

(1 comment)

> What is the symptom without this change? I.e. what is the full
 > error message?

external git returns exit code 128, and the tests fail with the not very helpful message

  java.lang.AssertionError: External git failed expected:<0> but was:<128>
        at org.junit.Assert.fail(Assert.java:88)
        ...

With the changed assertion, we also get the stderr in the log, and the tests fail with

  org.junit.ComparisonFailure: External git failed expected:<exit [0]
  > but was:<exit [128
  error: could not expand include path '~/.gitcinclude'
  fatal: bad config line 45 in file /usr/local/git/etc/gitconfig]
  >
        at org.junit.Assert.assertEquals(Assert.java:115)
        ...

which is a bit more helpful and points to a problem with substituting ~/. Setting $HOME for the call to external git resolves the problem and the tests pass. (I have git 2.13.1 installed on my Mac, and line 45 is an include of ~/.gitcinclude.)

In mvn this problem didn't exist since mvn doesn't do any sandboxing for tests. Nor does Eclipse when the test is run from within Eclipse.

Patch-set: 1