Update patch set 3
Patch Set 3:

on MacOS the javadoc generation fails with this error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.3.1:jar (default) on project org.eclipse.jgit: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /Users/xxx/src/git/jgit/org.eclipse.jgit/src/org/eclipse/jgit/util/IO.java:33: error: class IO clashes with package of same name
[ERROR] public class IO {
[ERROR]        ^
[ERROR]
[ERROR] Command line was: /Users/xxx/.sdkman/candidates/java/11.0.11.hs-adpt/bin/javadoc -Xdoclint:-missing @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in '/Users/xxx/src/git/jgit/org.eclipse.jgit/target/apidocs' dir.

Any idea how to fix this without renaming IO.java which would be a breaking change ?

Patch-set: 3
Reviewer: Gerrit User 4 <4@97ee7c02-f12f-4043-b43e-dea463d88b31>