StoredObjectRepresentationNotAvailableException: Remove unused parameter
Both constructors take an ObjectToPack, but it is not referenced in the
constructor or stored as a reference.

Also, the ObjectToPack class is not API, and Eclipse reports a warning
about its use.

Remove the deprecated and unused constructor, and remove ObjectToPack
from the remaining one.

Change-Id: I6031fec49cfd15b3e0d891109c9e7a5597e0ef0f
Signed-off-by: David Pursehouse <david.pursehouse@gmail.com>