Fix DepthGenerator navigation for unshallow commits
During the navigation of commits reachable by two or more paths, the
unshallow operation was wrongly returning the same commits multiple
times, even if they were flagged as UNINTERESTING.

Example use-case:

     [v0.14.0]
      |
      v
A --- B --- C <-[master]
        \
         \
          --- D <- [v0.14.1]

The commit B is UNSHALLOW and is reachable by both [master] and
[v0.14.1], therefore is reachable twice.

Before this change, the presence of the UNSHALLOW flag on B was causing
the commit B to be returned twice from the navigation, once from B and
the second time from C.

Returning the commit B twice, caused confusion in the TopoSortGenerator
that assumed its parent commit A was reachable by two different paths,
whilst that was not the case.

The chain of events, caused the TopoSortGenerator to buffer the commit A
and never returning it, assuming that it needed to wait for all its
parent objects to returned first (topological sorting).
From a client's perspective, this was visible with the 'unshallow'
command failing with:

error: Could not read (SHA1 of A)
fatal: Failed to traverse parents of commit (SHA1 of B)

With this fix, the UNSHALLOW flag is consumed once for assuring that the
UNINTERESTING objects included in the 'have' from the Git client are
still returned *once* but without duplicates.

Bug: jgit-182
Change-Id: Ie934ebfdc8ed53edeefeb03d64d92813e0adff55
Signed-off-by: Luca Milanesio <luca.milanesio@gmail.com>