PatchApplier.Result.Error: mark fields final
Fields of an Error instance shouldn't be modifiable after its creation.
We can't mark hh final since it's set to null in some tests to skip
asserting the hunk header which is a complex object with lots of
internal state.

Change-Id: I0f55c1d5cd529aa510029054e6f05bd2637d1bca