Disable BOUNDARY and TOPO sort for unshallow fetches
When a PackWriter is used for serving an unshallow request, the commits
passed in the HAVE part of the requests are flagged as UNINTERESTING;
however, the unshallow requests should keep the navigation going and
just filter the HAVE commits out. However, the BOUNDARY and TOPO sort
strategies are implemented by the TopoSortGenerator and
BoundaryGenerator classes were never adapted to support the unshallow
requests, therefore are treating these requests as regular fetch and do
not complete the navigation as needed, resulting in omitting commits
needed by the client to complete the unshallow.

The broken navigation can causes multiple issues, one of them is the
navigation of commits reachable by two or more paths, where the
combination of TopoSortGenerator and BoundaryGenerator was interfering
with the normal DepthGenerator of unshallow requests.

Example use-case:

     [v0.14.0]
      |
      v
A --- B --- C <-[master]
        \
         \
          --- D <- [v0.14.1]

The commit B is UNSHALLOW and is reachable by both [master] and
[v0.14.1], therefore, is reachable twice. The DepthGenerator keeps some
reference counting on the RevObject to keep track of the commit depth
navigation of unshallow requests.

The BoundaryGenerator and TopoSortGenerator, which were never adapted to
support that unshallow requests, as seen in [1], therefore should not be
used yet until they are properly adapted of the unshallow commits.

From an E2E client's perspective, this specific issue was visible with
the 'git fetch --unshallow' command failing with:

error: Could not read (SHA1 of A) fatal: Failed to traverse parents of
commit (SHA1 of B)

After this Change, the PackWriter does not request the BOUNDARY and TOPO
sorting and just relying on the DepthGenerator, which works as expected
and continues the navigation, returning all the commits needed to serve
the client.

References: [1] https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1320

Bug: jgit-182
Change-Id: Iacf3d06fd021b7548a1dd4ecc27151d0b20e4b10
Signed-off-by: Luca Milanesio <luca.milanesio@gmail.com>