Update patch set 5
Patch Set 5:

> Patch Set 5: Code-Review+1
> 
> PS5 adds the missing repo close in GcTestCase.
> 
> In pgm, FetchTest and RemoteTest cannot remove the git directory on Windows because there are still open file handles on a pack file after the repo is closed. This will need to be fixed in a later change. I do notice that the ObjectReader created in ObjectWalk(Repository) is never closed, but fixing that alone doesn't solve that problem. When I run these tests with breakpoints in Pack.doOpen() and Pack.doClose(), only the breakpoint in doOpen() is hit. doClose() is not called.
> 
> So clearly there is more to do to get all tests working on Windows. But at least repo closing should be fine now.

I still see a lot of failures with this CL on Windows. Though, may be I am missing something in my environment. For example AddCommandTest#testCleanFilter() is createing script with "sed" command and is failing here with:

  org.eclipse.jgit.api.errors.FilterFailedException: Execution of filter command
  'sh C:/Users/dostr/AppData/Local/Temp/AddCommandTest_12364323373600314320'
  on file 'src/a.txt' failed with return code '1', message on stderr:
  'Der Befehl "sh" ist entweder falsch geschrieben oder konnte nicht gefunden werden.'
  at org.eclipse.jgit.treewalk.WorkingTreeIterator.filterClean(WorkingTreeIterator.java:505)
  [...]

Should cygwin, msys2 or mingw be provided on the path? Are the prerequisites documented for the test to succeed?

Patch-set: 5