Update patch set 1
Patch Set 1:

> The implementation is thread-safe, so you can do
 > 
 > @SuppressWarnings("UnsynchronizedOverridesSynchronized") // This
 > stub implementation is thread-safe.
 > 
 > Is this method ever called? Could it throw UnsupportedOperationException
 > instead?

By reading the code, I thought it should not be called, but after adding a fail() in there I can see that in fact it is called:

 1) testSkip(org.eclipse.jgit.util.io.UnionInputStreamTest)
 java.lang.AssertionError: unexpected call to skip()

Patch-set: 1