ReceivePack: reject creation of one level refs such as refs/main
Cgit describes valid reference names in the `git-check-ref-format(1)`
manual page which lists the constraints. Excluding the `refs/` prefix,
the name must contain at least one slash to enforce a category such as
`heads/`, `tags/`.

On Gerrit, jGit accepts a user pushing to `refs/main` but when
replicating the reference using ssh and cgit, receive-pack on the remote
rejects it with:

 Error: Failed replicate of refs/main to X, reason: funny refname

It is a special case in cgit `builtin/receive-pack.c`:

--------8<-----------8<-----------8<-----------8<-----------8<-----------
static const char *update(struct command *cmd, struct shallow_info *si)
{
...
        /* only refs/... are allowed */
        if (!starts_with(name, "refs/") || check_refname_format(name + 5, 0)) {
                rp_error("refusing to create funny ref '%s' remotely", name);
                return "funny refname";
        }
--------8<-----------8<-----------8<-----------8<-----------8<-----------

So that if the part coming after `refs/` has a single component
(`master`) it is rejected.

Bug: 582000
Change-Id: Ica2bdc58e81459f08cfe42c2961a3c06622c30df