Don't use localized String during JVM shutdown
During shutdown the JGitText class may already be unloaded causing NoClassDefFoundError.

See https://github.com/eclipse-jgit/jgit/issues/17 / https://github.com/eclipse-jgit/jgit/issues/36