[errorprone] Demote InvalidBlockTag to WARN
Since 3764cd5711679e328499656c760ebda40a42a1f0 raises an error

org.eclipse.jgit/src/org/eclipse/jgit/revwalk/RevWalk.java:1768: error:
[InvalidBlockTag] Tag name `nooverride` is unknown. If this is a
commonly-used custom tag, please click 'not useful' and file a bug.
	 * @nooverride Since 7.8 This method is not intended to be
re-implemented or
	   ^
    (see https://errorprone.info/bugpattern/InvalidBlockTag)

`RevWalk.createCommit(AnyObjectId)` was marked with the javadoc tag
@nooverride which is understood by Eclipse API tooling [1].
It will ensure that API tools raise an error if another bundle extends
or re-implements the method marked with this tag.

Hence demote the severity of InvalidBlockTag to WARN.

[1] https://github.com/eclipse-pde/eclipse.pde/blob/master/docs/API_Tools.md

Change-Id: I95ade650c3ac1e2301654970cae09cc49f6d3af9