Update patch set 4
Patch Set 4:

> https://hudson.eclipse.org/jgit/job/jgit.gerrit/7858/ : FAILURE

Maven build fails because of

  java.io.IOException: Could not create temp dir /tmp/tycho8066287481999886670equinox

No idea what that's about...

Patch-set: 4
Label: Verified=0