Update patch set 3
Patch Set 3:

> P.S. The packfile is 100% fine, I checked it with git verify-pack. After a while, JGit tries to reload the packfile and it is all fine. Not clear to me why it has been previously flagged as invalid.
> 
> The problem is the transitory moment when JGit "believes" that the packfile is invalid, flags it as invalid in memory and then removes from the list, without reloading it again.

I added more logs and this is the reason why the packfile was flagged as invalid:

org.eclipse.jgit.errors.PackMismatchException: Pack object count mismatch: pack 6f719c50dc701ac904db90330b687c0536e3a27e index 27441a6f9776584ecb698daeddb261a686c6bb02: /var/gerrit/git/All-Users.git/objects/pack/pack-60be33b0b453c89a7ba6d62b9c490dad71d7e022.pack
        at org.eclipse.jgit.internal.storage.file.PackFile.onOpenPack(PackFile.java:763)
        at org.eclipse.jgit.internal.storage.file.PackFile.doOpen(PackFile.java:651)
        at org.eclipse.jgit.internal.storage.file.PackFile.beginWindowCache(PackFile.java:631)
        at org.eclipse.jgit.internal.storage.file.WindowCache.load(WindowCache.java:295)

It seems that during GC the packfile and the index may be out of sync?

Patch-set: 3