Update patch set 9
Patch Set 9:

> thanks, this works fine on Java 10,
 > 
 > On Java 11 I hit this error
 > 
 > ERROR: org.eclipse.jgit/BUILD:16:1: Building org.eclipse.jgit/libjgit-class.jar
 > (822 source files) failed (Exit 1)
 > error: module not found: java.xml.bind
 > 
 > though I think this is not caused by bazel or bazel configuration
 > but needs changes in WalkEncryption which is using classes from
 > this package which is no longer part of JDK 11

Right. As explained here: [1] and here: [2], we need to add extra dependencies starting from Java 11 support instead trying to open java.xml.bind module using this parameter: --add-modules=java.xml.bind.

* [1] https://blog.codefx.org/java/java-11-migration-guide/
* [2] https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis/48204154#48204154

Patch-set: 9