Update patch set 1
Patch Set 1:

Could the following EGit test failure also be caused by changes in hamcrest?:

https://hudson.eclipse.org/sandbox/job/egit.gerrit/4604/testReport/org.eclipse.egit.ui.test.history/HistoryViewTest/testRebaseAlreadyUpToDate/

java.lang.NoSuchMethodError: org.hamcrest.Matchers.allOf(Lorg/hamcrest/Matcher;Lorg/hamcrest/Matcher;)Lorg/hamcrest/Matcher;
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot.contextMenu(AbstractSWTBot.java:448)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotTableItem.contextMenu(SWTBotTableItem.java:145)
	at org.eclipse.egit.ui.test.history.HistoryViewTest.testRebaseAlreadyUpToDate(HistoryViewTest.java:384)

Patch-set: 1