Update patch set 23
Patch Set 23:

> > > > Most of the tests are failing with timeout when I run `bazel
 > > test
 > > > > //...` on OSX, and git bisect says it was caused by this
 > > commit.
 > > >
 > > > same here, looks like saving measured resolution to
 > ~/.gitconfig
 > > > does not work
 > >
 > > could this be caused by bazel sandboxing ?
 > > https://blog.bazel.build/2015/09/11/sandboxing.html
 > 
 > LockFile.lock() seems to fail, lock file is created but acquiring
 > the lock doesn't succeed

Patches [1] reveal the reason.: creating lock file for ~/.gitconfig fails [2] due to bazel sandboxing.
Running tests with option --spawn_strategy=standalone works around this problem [1].

[1]
https://git.eclipse.org/r/#/c/147398
https://git.eclipse.org/r/#/c/147399

[2] 
23:06:31.462Z [ForkJoinPool.commonPool-worker-1] ERROR org.eclipse.jgit.internal.storage.file.LockFile - Creating lock file /Users/msohn/.gitconfig.lock failed
java.io.IOException: Operation not permitted
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.eclipse.jgit.util.FS_POSIX.createNewFileAtomic(FS_POSIX.java:446)
	at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:169)
	at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:260)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig(FS.java:578)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$getFileStoreAttributes$1(FS.java:357)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[3] https://docs.bazel.build/versions/master/user-manual.html#flag--spawn_strategy

Patch-set: 23