Repository: reject one level refs such as refs/main
Cgit describes valid reference names in the `git-check-ref-format(1)`
manual page which lists the constraints. Excluding the `refs/` prefix,
the name must contain at least one slash to enforce a category such as
`heads/`, `tags/`.

On Gerrit, jGit accepts a user pushing to `refs/main` but replicating
the reference using ssh and cgit receive-pack on the remote would fail
with:

 Error: Failed replicate of refs/main to X, reason: funny refname

The ValidRefNameTest test expects `heads/master` to be valid which is
breaking the contract. I don't know how exactly that was coded but I
think the original author had `refs/` taken in account which makes the
result off by one. The issue was introduced in the very first commit of
this repo: 1a6964c8274c50f0253db75f010d78ef0e739343.

094df5a916db6060fa7f7d8c1f61cc0b970a9433 added a validation for the
components names (eg `heads`, `tags`) and uses a hardcoded `x/` prefix
to validate the component. Update all of them to `refs/x/`. Ideally it
should be new method dedicated at validating a component name without
requiring the prefix (which is how cgit does it).

Bug: 582000
Change-Id: Ica2bdc58e81459f08cfe42c2961a3c06622c30df