Update patch set 2
Patch Set 2:

If the refName is a short name like "master", the tests now fail with 

  org.eclipse.jgit.api.errors.TransportException: Remote does not have master available for fetch.

in CloneCommandTest and PullCommandTest. PullCommandWithRebaseTest also fails.

Patch-set: 2
Reviewer: Gerrit User 44628 <44628@97ee7c02-f12f-4043-b43e-dea463d88b31>